### ISSUE TITLE
build error: Error: ENOENT, no such file or directory '/usr/local/haraka/config/smtp.ini'

### ISSUE THREAD

**Issue by nmpgaspar** [wallix/PEPS#76]
Hello. 

I'm running Ubuntu 16.04, and getting the following error while compiling:

...
Step 13/23 : RUN haraka -i /usr/local/haraka
 ---> Running in fc4eee9accc0
copy /usr/lib/node_modules/Haraka/config/smtp.ini to /usr/local/haraka/config/smtp.ini

/usr/lib/node_modules/Haraka/bin/haraka:201
            throw e;
                  ^
Error: ENOENT, no such file or directory '/usr/local/haraka/config/smtp.ini'
    at Object.fs.statSync (fs.js:696:18)
    at copyFile (/usr/lib/node_modules/Haraka/bin/haraka:185:16)
    at setupBaseConfig (/usr/lib/node_modules/Haraka/bin/haraka:224:5)
    at Object.<anonymous> (/usr/lib/node_modules/Haraka/bin/haraka:667:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
The command '/bin/sh -c haraka -i /usr/local/haraka' returned a non-zero code: 8
Makefile:41: recipe for target 'build' failed
make: *** [build] Error 8

Any idea what I may be doing wrong or missing?

**Comment by insideTheFlux** [comment]
I too am getting that very same error. I tried re-running the 'make build' command again and no joy.

thanks.

===================================

Step 13/23 : RUN haraka -i /usr/local/haraka
 ---> Running in 38cc6209dfd4
copy /usr/lib/node_modules/Haraka/config/smtp.ini to /usr/local/haraka/config/smtp.ini

/usr/lib/node_modules/Haraka/bin/haraka:201
            throw e;
                  ^
Error: ENOENT, no such file or directory '/usr/local/haraka/config/smtp.ini'
    at Object.fs.statSync (fs.js:696:18)
    at copyFile (/usr/lib/node_modules/Haraka/bin/haraka:185:16)
    at setupBaseConfig (/usr/lib/node_modules/Haraka/bin/haraka:224:5)
    at Object.<anonymous> (/usr/lib/node_modules/Haraka/bin/haraka:667:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
The command '/bin/sh -c haraka -i /usr/local/haraka' returned a non-zero code: 8
Makefile:41: recipe for target 'build' failed
make: *** [build] Error 8
=============================

**Comment by gtrr34** [comment]
Hi...
Have same problem:

> centos-release-6-8.el6.centos.12.3.x86_64



```
 ---> Running in ab26f1a0a838
copy /usr/lib/node_modules/Haraka/config/smtp.ini to /usr/local/haraka/config/smtp.ini

/usr/lib/node_modules/Haraka/bin/haraka:201
            throw e;
                  ^
Error: ENOENT, no such file or directory '/usr/local/haraka/config/smtp.ini'
    at Object.fs.statSync (fs.js:696:18)
    at copyFile (/usr/lib/node_modules/Haraka/bin/haraka:185:16)
    at setupBaseConfig (/usr/lib/node_modules/Haraka/bin/haraka:224:5)
    at Object.<anonymous> (/usr/lib/node_modules/Haraka/bin/haraka:667:5)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
The command '/bin/sh -c haraka -i /usr/local/haraka' returned a non-zero code: 8
make: *** [build] Error 1

**Comment by insideTheFlux** [comment]
I fixed my problem by getting mail-in-a-box setup instead. I also have another setup that I setup manually. PEPs is obsolete and a deprecated product. ciao!

**Comment by gtrr34** [comment]
Can you point to the direction on how you did it manually?

**Comment by insideTheFlux** [comment]
I did not use peps is what I'm saying. Mail-in-a-box. check it out. Then I followed https://skrilnetz.net/setup-your-own-mailserver/ on another server for manual install. I put nextcloud in there and voila. I ditched peps completely, I don't use it.

**Comment by gtrr34** [comment]
@insideTheFlux Thanks!

**Comment by hbbio** [comment]
This implementation is not maintained anymore.

We will release a new version in June 2017.

**Comment by gtrr34** [comment]
@hbbio Hi, any working versions right now available?

**Comment by hbbio** [comment]
APIs are done and tested and they will launch separately. The front (now in React) is not yet usable, we expect a beta release early May.

**Comment by camidusinc** [comment]
Hello @hbbio , reading this thread and getting stuck with the same error. When will the new version be released ?
